// Types matching iOS Models.swift

export interface User {
  id: string;
  name: string;
  email: string;
  avatarURL?: string;
}

export type ThemeMode = 'light' | 'dark' | 'system';

export interface UserPreferences {
  theme: ThemeMode;
  autoSummary: boolean;
  defaultLanguage: string;
  enableNotifications: boolean;
}

export interface Folder {
  id: string;
  name: string;
  color: string;
  parentId?: string;
  userId: string;
  createdAt: Date;
  fileCount: number;
}

export interface Tag {
  id: string;
  name: string;
  color: string;
  userId: string;
  createdAt: Date;
  fileCount: number;
  isAutoGenerated: boolean;
}

export interface PDFDocumentMetadata {
  id: string;
  name: string;
  size: number;
  uploadedAt: Date;
  storagePath: string;
  thumbnailData?: string;
  summary?: string;
  folderId?: string;
  tags: Tag[];
  aiCategory?: string;
}

export type AnnotationType = 'highlight' | 'underline' | 'strikethrough';

export interface AnnotationRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Annotation {
  id: string;
  fileId: string;
  pageNumber: number;
  type: AnnotationType;
  color: string;
  rects: AnnotationRect[];
  text?: string;
  note?: string;
  isAiGenerated: boolean;
  createdAt: Date;
  updatedAt?: Date;
}

export type MessageRole = 'user' | 'model';

export interface ChatMessage {
  id: string;
  role: MessageRole;
  text: string;
  timestamp: Date;
  attachment?: {
    type: 'image';
    content: string;
  };
}

export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation?: string;
}

export interface TranslationResult {
  original: string;
  translated: string;
  detectedLanguage: string;
}

export interface SelectionData {
  text: string;
  rect: { x: number; y: number; width: number; height: number };
  pageNumber: number;
}

// Highlight colors matching iOS
export const HIGHLIGHT_COLORS = {
  yellow: '#fef08a',
  green: '#bbf7d0',
  blue: '#bae6fd',
  pink: '#fbcfe8',
} as const;

// Supabase database types
export interface DatabaseFileRecord {
  id: string;
  user_id: string;
  name: string;
  size: number;
  storage_path: string;
  thumbnail_base64?: string;
  summary?: string;
  folder_id?: string;
  ai_category?: string;
  created_at: string;
  updated_at?: string;
}

// Nested data structure used by mobile app in JSONB column
export interface DatabaseAnnotationData {
  color: string;
  rects: AnnotationRect[];
  text?: string;
  note?: string;
  isAiGenerated?: boolean;
}

// Matches mobile schema: uses 'page' column and 'data' JSONB column
export interface DatabaseAnnotation {
  id: string;
  file_id: string;
  user_id?: string;
  page: number;  // Mobile uses 'page', not 'page_number'
  type: string;  // Stored as string in DB
  data: DatabaseAnnotationData;  // Nested JSONB column
  created_at: string;
}

export interface DatabaseFolder {
  id: string;
  user_id: string;
  name: string;
  color: string;
  parent_id?: string;
  created_at: string;
}

export interface DatabaseTag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  is_auto_generated: boolean;
  created_at: string;
}

export interface DocumentChunk {
  id: string;
  fileId: string;
  chunkIndex: number;
  content: string;
  pageNumber?: number;
  similarity?: number;
}
