# SwiftLint Configuration for PolyglotReader
# Based on RULES.md and Airbnb Swift Style Guide
# Last updated: 2026-01-03

# ============================================
# EXCLUDED PATHS
# ============================================
excluded:
  - .build
  - DerivedData
  - .git
  - Pods
  - Carthage
  - .swiftpm
  - Package.swift
  - "*.generated.swift"
  # TECH-DEBT: Large view/utility files pending cleanup (Phase 2)
  - PolyglotReader/Views/Reader/PDFReaderView.swift
  - PolyglotReader/Views/Chat/MarkdownView.swift
  - PolyglotReader/Services/LoggingService.swift
  - PolyglotReader/Views/Reader/QuickTranslationPopup.swift
  - PolyglotReader/Views/Library/FlippablePDFCardView.swift

# ============================================
# INCLUDED PATHS
# ============================================
included:
  - PolyglotReader

# ============================================
# RULE CONFIGURATION - STRICT VALUES
# ============================================

# MARK: - Length Rules (per RULES.md requirements)

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true
  ignores_interpolated_strings: true

large_tuple:
  warning: 3
  error: 5

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

function_body_length:
  warning: 40
  error: 60

type_body_length:
  warning: 350
  error: 500

# MARK: - Force Rules (RULES.md: Force unwrap yasak)
# These are set to ERROR level as per RULES.md requirements

force_cast: error
force_try: error
# Note: force_unwrapping is enabled in opt_in_rules below

# MARK: - Style Rules

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

trailing_newline: warning

colon:
  apply_to_dictionaries: true

comma: warning

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true
  excluded:
    - id
    - ok
    - x
    - y
    - i
    - to
    - at

# MARK: - Code Quality Rules

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# MARK: - Swift Best Practices

implicit_return: warning

closure_parameter_position: warning

empty_count: warning

implicit_optional_initialization: warning

unused_optional_binding: warning

weak_delegate: warning

# ============================================
# DISABLED RULES WITH JUSTIFICATION
# ============================================

disabled_rules:
  # Disabled: Turkish documentation comments don't match English patterns
  - missing_docs
  
  # Disabled: Some SwiftUI views require long constructors
  - function_parameter_count
  
  # Disabled: Conflicts with SwiftUI's opaque return types
  - explicit_type_interface

# ============================================
# OPT-IN RULES
# ============================================

opt_in_rules:
  # Force unwrapping - CRITICAL per RULES.md
  - force_unwrapping
  # Weak delegate
  - weak_delegate
  # Code cleanliness
  - empty_count
  - explicit_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# ============================================
# CUSTOM RULES
# ============================================

custom_rules:
  # RULES.md: print() statements in production - LoggingService kullan
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\s*\('
    message: "Use LoggingService (logDebug, logInfo, logWarning, logError) instead of print()"
    severity: warning
    
  # RULES.md: API keys in source code
  no_hardcoded_api_keys:
    name: "No Hardcoded API Keys"
    regex: '(api[_-]?key|apikey|secret[_-]?key)\s*[:=]\s*"[^"]{20,}"'
    message: "API keys should be stored in Config.plist, not hardcoded"
    severity: error
    match_kinds:
      - string
      
  # RULES.md: Hardcoded strings for user-facing text
  no_hardcoded_user_strings:
    name: "Consider Localization"
    regex: 'Text\s*\(\s*"[^"]{30,}"'
    message: "Consider using localized strings for user-facing text"
    severity: warning

# ============================================
# ANALYZER RULES
# ============================================

analyzer_rules:
  - unused_import
  - unused_declaration

# Reporter type
reporter: "xcode"
