'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { getSupabase } from '@/lib/supabase';
import { PDFDocumentMetadata, Folder, Tag, DatabaseFileRecord, DatabaseFolder, DatabaseTag } from '@/types/models';

const PAGE_SIZE = 30;

interface UseDocumentsReturn {
    documents: PDFDocumentMetadata[];
    folders: Folder[];
    tags: Tag[];
    isLoading: boolean;
    error: string | null;
    selectedFolder: string | null;
    selectedTag: string | null;
    searchQuery: string;
    hasMore: boolean;
    loadMore: () => void;
    setSelectedFolder: (id: string | null) => void;
    setSelectedTag: (id: string | null) => void;
    setSearchQuery: (query: string) => void;
    refresh: () => Promise<void>;
}

export function useDocuments(): UseDocumentsReturn {
    const [documents, setDocuments] = useState<PDFDocumentMetadata[]>([]);
    const [folders, setFolders] = useState<Folder[]>([]);
    const [tags, setTags] = useState<Tag[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [selectedFolder, setSelectedFolder] = useState<string | null>(null);
    const [selectedTag, setSelectedTag] = useState<string | null>(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [debouncedSearch, setDebouncedSearch] = useState('');
    const [hasMore, setHasMore] = useState(true);
    const [page, setPage] = useState(0);
    const foldersLoadedRef = useRef(false);

    const supabase = getSupabase();

    const mapDocument = (record: DatabaseFileRecord): PDFDocumentMetadata => ({
        id: record.id,
        name: record.name,
        size: record.size,
        uploadedAt: new Date(record.created_at),
        storagePath: record.storage_path,
        thumbnailData: record.thumbnail_base64,
        summary: record.summary,
        folderId: record.folder_id,
        aiCategory: record.ai_category,
        tags: [],
    });

    const mapFolder = (record: DatabaseFolder): Folder => ({
        id: record.id,
        name: record.name,
        color: record.color,
        parentId: record.parent_id,
        userId: record.user_id,
        createdAt: new Date(record.created_at),
        fileCount: 0,
    });

    const mapTag = (record: DatabaseTag): Tag => ({
        id: record.id,
        name: record.name,
        color: record.color,
        userId: record.user_id,
        createdAt: new Date(record.created_at),
        fileCount: 0,
        isAutoGenerated: record.is_auto_generated,
    });

    // Debounce search query (300ms)
    useEffect(() => {
        const timer = setTimeout(() => setDebouncedSearch(searchQuery), 300);
        return () => clearTimeout(timer);
    }, [searchQuery]);

    // Fetch folders and tags only once on mount
    useEffect(() => {
        if (foldersLoadedRef.current) return;
        foldersLoadedRef.current = true;

        const fetchFoldersAndTags = async () => {
            try {
                const [foldersResult, tagsResult] = await Promise.all([
                    supabase.from('folders').select('*').order('name'),
                    supabase.from('tags').select('*').order('name'),
                ]);

                if (!foldersResult.error) {
                    setFolders((foldersResult.data || []).map(mapFolder));
                }
                if (!tagsResult.error) {
                    setTags((tagsResult.data || []).map(mapTag));
                }
            } catch {
                // Folders/tags fetch failure is non-critical
            }
        };

        fetchFoldersAndTags();
    }, [supabase]);

    // Reset pagination when filter changes
    useEffect(() => {
        setPage(0);
        setDocuments([]);
        setHasMore(true);
    }, [selectedFolder, debouncedSearch]);

    // Fetch documents with pagination
    const fetchDocuments = useCallback(async (pageNum: number = 0) => {
        setIsLoading(true);
        setError(null);

        try {
            const from = pageNum * PAGE_SIZE;
            const to = from + PAGE_SIZE - 1;

            let documentsQuery = supabase
                .from('files')
                .select('*')
                .order('created_at', { ascending: false })
                .range(from, to);

            if (selectedFolder) {
                documentsQuery = documentsQuery.eq('folder_id', selectedFolder);
            }

            if (debouncedSearch) {
                documentsQuery = documentsQuery.ilike('name', `%${debouncedSearch}%`);
            }

            const docsResult = await documentsQuery;

            if (docsResult.error) throw docsResult.error;

            const newDocs = (docsResult.data || []).map(mapDocument);
            setHasMore(newDocs.length === PAGE_SIZE);

            if (pageNum === 0) {
                setDocuments(newDocs);
            } else {
                setDocuments(prev => [...prev, ...newDocs]);
            }
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Dosyalar yüklenemedi');
        } finally {
            setIsLoading(false);
        }
    }, [supabase, selectedFolder, debouncedSearch]);

    useEffect(() => {
        fetchDocuments(page);
    }, [fetchDocuments, page]);

    const loadMore = useCallback(() => {
        if (!isLoading && hasMore) {
            setPage(prev => prev + 1);
        }
    }, [isLoading, hasMore]);

    const refresh = useCallback(async () => {
        // On manual refresh, also reload folders/tags
        try {
            const [foldersResult, tagsResult] = await Promise.all([
                supabase.from('folders').select('*').order('name'),
                supabase.from('tags').select('*').order('name'),
            ]);
            if (!foldersResult.error) {
                setFolders((foldersResult.data || []).map(mapFolder));
            }
            if (!tagsResult.error) {
                setTags((tagsResult.data || []).map(mapTag));
            }
        } catch {
            // Non-critical
        }
        setPage(0);
        setHasMore(true);
        await fetchDocuments(0);
    }, [supabase, fetchDocuments]);

    return {
        documents,
        folders,
        tags,
        isLoading,
        error,
        selectedFolder,
        selectedTag,
        searchQuery,
        hasMore,
        loadMore,
        setSelectedFolder,
        setSelectedTag,
        setSearchQuery,
        refresh,
    };
}
