import Foundation
import PDFKit
@testable import PolyglotReader

/// Factory for creating test data objects
enum TestDataFactory {
    
    // MARK: - User
    
    static func makeUser(
        id: String = UUID().uuidString,
        name: String = "Test User",
        email: String = "test@example.com",
        avatarURL: URL? = nil
    ) -> User {
        User(
            id: id,
            name: name,
            email: email,
            avatarURL: avatarURL
        )
    }
    
    // MARK: - PDF Document Metadata
    
    static func makePDFMetadata(
        id: String = UUID().uuidString,
        name: String = "Test Document.pdf",
        size: Int = 1024 * 1024,  // 1MB
        uploadedAt: Date = Date(),
        storagePath: String = "pdfs/test-doc.pdf",
        thumbnailData: Data? = nil,
        summary: String? = "Test document summary",
        folderId: UUID? = nil,
        tags: [Tag] = [],
        aiCategory: String? = nil
    ) -> PDFDocumentMetadata {
        PDFDocumentMetadata(
            id: id,
            name: name,
            size: size,
            uploadedAt: uploadedAt,
            storagePath: storagePath,
            thumbnailData: thumbnailData,
            summary: summary,
            folderId: folderId,
            tags: tags,
            aiCategory: aiCategory
        )
    }
    
    // MARK: - Annotation
    
    static func makeAnnotation(
        id: String = UUID().uuidString,
        fileId: String = UUID().uuidString,
        pageNumber: Int = 1,
        type: AnnotationType = .highlight,
        color: String = "#fef08a",
        rects: [AnnotationRect] = [AnnotationRect(x: 10, y: 20, width: 100, height: 20)],
        text: String? = "Highlighted text",
        note: String? = nil,
        isAiGenerated: Bool = false,
        createdAt: Date = Date(),
        updatedAt: Date? = nil
    ) -> Annotation {
        Annotation(
            id: id,
            fileId: fileId,
            pageNumber: pageNumber,
            type: type,
            color: color,
            rects: rects,
            text: text,
            note: note,
            isAiGenerated: isAiGenerated,
            createdAt: createdAt,
            updatedAt: updatedAt
        )
    }
    
    // MARK: - Chat Message
    
    static func makeChatMessage(
        id: String = UUID().uuidString,
        role: ChatMessage.MessageRole = .user,
        text: String = "Test message",
        timestamp: Date = Date()
    ) -> ChatMessage {
        ChatMessage(
            id: id,
            role: role,
            text: text,
            timestamp: timestamp
        )
    }
    
    static func makeUserMessage(text: String = "User question") -> ChatMessage {
        makeChatMessage(role: .user, text: text)
    }
    
    static func makeModelMessage(text: String = "AI response") -> ChatMessage {
        makeChatMessage(role: .model, text: text)
    }
    
    // MARK: - Folder
    
    static func makeFolder(
        id: UUID = UUID(),
        name: String = "Test Folder",
        color: String = "#6366F1",
        parentId: UUID? = nil,
        userId: String = UUID().uuidString,
        createdAt: Date = Date(),
        fileCount: Int = 0
    ) -> Folder {
        Folder(
            id: id,
            name: name,
            color: color,
            parentId: parentId,
            userId: userId,
            createdAt: createdAt,
            fileCount: fileCount
        )
    }
    
    // MARK: - Tag
    
    static func makeTag(
        id: UUID = UUID(),
        name: String = "Test Tag",
        color: String = "#22C55E",
        userId: String = UUID().uuidString,
        createdAt: Date = Date(),
        fileCount: Int = 0,
        isAutoGenerated: Bool = false
    ) -> Tag {
        Tag(
            id: id,
            name: name,
            color: color,
            userId: userId,
            createdAt: createdAt,
            fileCount: fileCount,
            isAutoGenerated: isAutoGenerated
        )
    }
    
    // MARK: - Sample PDF Data
    
    static func makeSamplePDFData() -> Data {
        // Create a minimal valid PDF
        let pdfString = """
        %PDF-1.4
        1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
        2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
        3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >> endobj
        xref
        0 4
        0000000000 65535 f 
        0000000009 00000 n 
        0000000058 00000 n 
        0000000115 00000 n 
        trailer << /Size 4 /Root 1 0 R >>
        startxref
        193
        %%EOF
        """
        return pdfString.data(using: .utf8) ?? Data()
    }
    
    static func makeSamplePDFDocument() -> PDFDocument? {
        PDFDocument(data: makeSamplePDFData())
    }
}
