-- Add a monotonic tie-breaker for chat message ordering.
--
-- Both clients sort chats only by created_at; user/model rows written within
-- the same timestamp resolution reload in arbitrary order. seq is assigned by
-- the database on insert and is strictly increasing, so
-- ORDER BY created_at, seq is deterministic. Existing rows get backfilled
-- values in physical order, which only matters within equal timestamps —
-- exactly the previously-ambiguous case.
ALTER TABLE public.chats
    ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_chats_file_created_seq
    ON public.chats (file_id, created_at, seq);
