import Foundation
import Combine
import CoreGraphics

// MARK: - Annotation Stats
struct AnnotationStats: Codable {
    var total: Int = 0
    var highlights: Int = 0
    var notes: Int = 0
    var aiNotes: Int = 0
    var favorites: Int = 0
    var colorCounts: [String: Int] = [:]

    var yellowCount: Int { colorCounts["#fef08a"] ?? 0 }
    var greenCount: Int { colorCounts["#bbf7d0"] ?? 0 }
    var blueCount: Int { colorCounts["#bae6fd"] ?? 0 }
    var pinkCount: Int { colorCounts["#fbcfe8"] ?? 0 }
}

// MARK: - User Model
struct User: Codable, Identifiable {
    let id: String
    var name: String
    var email: String
    var avatarURL: URL?

    init(id: String, name: String, email: String, avatarURL: URL? = nil) {
        self.id = id
        self.name = name
        self.email = email
        self.avatarURL = avatarURL
    }

    /// Check if the user is an admin/developer.
    ///
    /// A client-side email allowlist is trivially bypassable, so admin-gated
    /// surfaces (e.g. Debug Logs export) are only exposed in DEBUG builds.
    /// Any production admin capability must be enforced server-side via Supabase
    /// RLS policies or a JWT role claim — never trusted from the client.
    var isAdmin: Bool {
        #if DEBUG
        let adminEmails = ["zsrgnunlu@gmail.com"]
        return adminEmails.contains(email.lowercased())
        #else
        return false
        #endif
    }
}

// MARK: - User Preferences
struct UserPreferences: Codable {
    var theme: ThemeMode = .system
    var autoSummary: Bool = true
    var defaultLanguage: String = "tr"
    var enableNotifications: Bool = true

    enum ThemeMode: String, Codable, CaseIterable {
        case light, dark, system

        var displayName: String {
            switch self {
            case .light: return "Açık"
            case .dark: return "Koyu"
            case .system: return "Sistem"
            }
        }
    }
}

// MARK: - Folder Model
struct Folder: Codable, Identifiable, Hashable {
    let id: UUID
    var name: String
    var color: String           // Hex renk kodu
    var parentId: UUID?         // İç içe klasörler için (opsiyonel)
    var userId: String
    var createdAt: Date
    var fileCount: Int
    var icon: String?           // SF Symbol (DB'de `folders.icon`; eski kayıtlar için nil)

    /// User-selected glyph: DB value first, then the legacy local store,
    /// then the default. Local store survives until the icon migration lands.
    var sfSymbol: String {
        icon ?? FolderIconStore.shared.icon(for: id) ?? "folder.fill"
    }

    init(
        id: UUID = UUID(),
        name: String,
        color: String = "#6366F1",
        parentId: UUID? = nil,
        userId: String,
        createdAt: Date = Date(),
        fileCount: Int = 0,
        icon: String? = nil
    ) {
        self.id = id
        self.name = name
        self.color = color
        self.parentId = parentId
        self.userId = userId
        self.createdAt = createdAt
        self.fileCount = fileCount
        self.icon = icon
    }
}

// MARK: - Tag Model
struct Tag: Codable, Identifiable, Hashable {
    let id: UUID
    var name: String
    var color: String           // Hex renk kodu
    var userId: String
    var createdAt: Date
    var fileCount: Int
    var isAutoGenerated: Bool

    init(
        id: UUID = UUID(),
        name: String,
        color: String = "#22C55E",
        userId: String,
        createdAt: Date = Date(),
        fileCount: Int = 0,
        isAutoGenerated: Bool = true
    ) {
        self.id = id
        self.name = name
        self.color = color
        self.userId = userId
        self.createdAt = createdAt
        self.fileCount = fileCount
        self.isAutoGenerated = isAutoGenerated
    }
}

// MARK: - PDF Document Metadata
struct PDFDocumentMetadata: Codable, Identifiable {
    let id: String
    var name: String
    var size: Int
    var uploadedAt: Date
    var storagePath: String
    var thumbnailData: Data?
    var summary: String?

    // Klasör ve Etiket Sistemi
    var folderId: UUID?
    var tags: [Tag]
    var aiCategory: String?

    // Favori ve Okuma İlerlemesi
    var isFavorite: Bool
    var pageCount: Int?         // files.page_count — eski kayıtlarda nil, lazy backfill
    var lastReadPage: Int?      // reading_progress.page
    var lastOpenedAt: Date?     // reading_progress.updated_at → "Son Açılan" sıralaması
    var deletedAt: Date?        // Soft delete: dolu ise dosya çöp kutusunda

    /// 0...1 arası okuma ilerlemesi; sayfa sayısı bilinmiyorsa nil.
    var readingProgress: Double? {
        guard let pageCount, pageCount > 0, let lastReadPage else { return nil }
        return min(1.0, Double(lastReadPage) / Double(pageCount))
    }

    var formattedSize: String {
        let formatter = ByteCountFormatter()
        formatter.allowedUnits = [.useKB, .useMB, .useGB]
        formatter.countStyle = .file
        return formatter.string(fromByteCount: Int64(size))
    }

    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.locale = Locale(identifier: "tr_TR")
        return formatter.string(from: uploadedAt)
    }

    init(
        id: String,
        name: String,
        size: Int,
        uploadedAt: Date,
        storagePath: String,
        thumbnailData: Data? = nil,
        summary: String? = nil,
        folderId: UUID? = nil,
        tags: [Tag] = [],
        aiCategory: String? = nil,
        isFavorite: Bool = false,
        pageCount: Int? = nil,
        lastReadPage: Int? = nil,
        lastOpenedAt: Date? = nil,
        deletedAt: Date? = nil
    ) {
        self.id = id
        self.name = name
        self.size = size
        self.uploadedAt = uploadedAt
        self.storagePath = storagePath
        self.thumbnailData = thumbnailData
        self.summary = summary
        self.folderId = folderId
        self.tags = tags
        self.aiCategory = aiCategory
        self.isFavorite = isFavorite
        self.pageCount = pageCount
        self.lastReadPage = lastReadPage
        self.lastOpenedAt = lastOpenedAt
        self.deletedAt = deletedAt
    }
}

// MARK: - Annotation
enum AnnotationType: String, Codable {
    case highlight
    case underline
    case strikethrough
}

/// One annotation rectangle as stored in Supabase (`annotations.data.rects`).
///
/// Canonical format — all NEW annotations from both iOS and web:
/// - Percentages (0-100) of the page as displayed, i.e. the cropBox with the
///   page rotation applied (what pdf.js renders), top-left origin.
///
/// Legacy format — old iOS annotations (values typically > 100):
/// - Raw PDFKit page-space points, bottom-left origin.
///
/// Read paths on both platforms distinguish the formats via the
/// "all values <= 100 → percentage" heuristic; conversion math lives in
/// `AnnotationCoordinateConverter`.
struct AnnotationRect: Codable {
    var x: CGFloat
    var y: CGFloat
    var width: CGFloat
    var height: CGFloat

    /// CGFloat değerini güvenli hale getirir (NaN, Infinity → 0)
    private static func sanitize(_ value: CGFloat) -> CGFloat {
        guard value.isFinite else { return 0 }
        return value
    }

    /// Geçerli bir rect mi kontrol eder
    var isValid: Bool {
        x.isFinite && y.isFinite && width.isFinite && height.isFinite &&
        width > 0 && height > 0
    }

    /// Debug amaçlı validasyon raporu
    var validationReport: String {
        var issues: [String] = []
        if !x.isFinite { issues.append("x=\(x)") }
        if !y.isFinite { issues.append("y=\(y)") }
        if !width.isFinite { issues.append("width=\(width)") }
        if !height.isFinite { issues.append("height=\(height)") }
        if width <= 0 { issues.append("width<=0") }
        if height <= 0 { issues.append("height<=0") }

        return issues.isEmpty ? "✅ Valid" : "❌ Issues: \(issues.joined(separator: ", "))"
    }

    // Custom Codable - NaN/Infinity değerlerini 0'a çevir
    enum CodingKeys: String, CodingKey {
        case x, y, width, height
    }

    init(x: CGFloat, y: CGFloat, width: CGFloat, height: CGFloat) {
        self.x = Self.sanitize(x)
        self.y = Self.sanitize(y)
        self.width = Self.sanitize(width)
        self.height = Self.sanitize(height)
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        x = Self.sanitize(try container.decode(CGFloat.self, forKey: .x))
        y = Self.sanitize(try container.decode(CGFloat.self, forKey: .y))
        width = Self.sanitize(try container.decode(CGFloat.self, forKey: .width))
        height = Self.sanitize(try container.decode(CGFloat.self, forKey: .height))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(Self.sanitize(x), forKey: .x)
        try container.encode(Self.sanitize(y), forKey: .y)
        try container.encode(Self.sanitize(width), forKey: .width)
        try container.encode(Self.sanitize(height), forKey: .height)
    }
}

struct Annotation: Codable, Identifiable {
    let id: String
    var fileId: String
    var pageNumber: Int
    var type: AnnotationType
    var color: String  // Hex color
    var rects: [AnnotationRect]
    var text: String?
    var note: String?
    var isAiGenerated: Bool
    var createdAt: Date
    var updatedAt: Date?

    init(
        id: String = UUID().uuidString,
        fileId: String,
        pageNumber: Int,
        type: AnnotationType,
        color: String,
        rects: [AnnotationRect],
        text: String? = nil,
        note: String? = nil,
        isAiGenerated: Bool = false,
        createdAt: Date = Date(),
        updatedAt: Date? = nil
    ) {
        self.id = id
        self.fileId = fileId
        self.pageNumber = pageNumber
        self.type = type
        self.color = color
        self.rects = rects
        self.text = text
        self.note = note
        self.isAiGenerated = isAiGenerated
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

// MARK: - Annotation JSON Safety Extension
extension Annotation {
    /// Returns a deep copy with all String properties safely re-allocated
    /// Prevents EXC_BAD_ACCESS from corrupted string backing storage during async operations
    /// CRITICAL: Uses JSON encode/decode to safely read all properties without direct access
    var safeForJSON: Annotation {
        // Property'lere direkt erişim crash'e neden oluyor
        // JSON encode/decode kullanarak tüm property'leri güvenli bir şekilde oku
        let encoder = JSONEncoder()
        let decoder = JSONDecoder()

        // Annotation'ı JSON'a encode et (property'lere güvenli erişim)
        guard let jsonData = try? encoder.encode(self),
              let decoded = try? decoder.decode(Annotation.self, from: jsonData) else {
            // Encode/decode başarısız olursa, fallback annotation oluştur
            return Annotation(
                id: UUID().uuidString,
                fileId: UUID().uuidString,
                pageNumber: 1,
                type: .highlight,
                color: "#fef08a",
                rects: [],
                text: nil,
                note: nil,
                isAiGenerated: false,
                createdAt: Date(),
                updatedAt: nil
            )
        }

        // Decoded annotation'ın tüm String property'lerini Data'ya çevirip tekrar String'e çevir
        // Bu, yeni memory allocation sağlar
        func safeString(_ str: String, fallback: String = "") -> String {
            guard let data = str.data(using: .utf8),
                  let safeStr = String(data: data, encoding: .utf8) else {
                return fallback
            }
            return safeStr
        }

        let colorValue = safeString(decoded.color, fallback: "#fef08a")
        let resolvedColor = colorValue.isEmpty ? "#fef08a" : colorValue

        return Annotation(
            id: safeString(decoded.id, fallback: UUID().uuidString),
            fileId: safeString(decoded.fileId, fallback: UUID().uuidString),
            pageNumber: decoded.pageNumber,
            type: decoded.type,
            color: resolvedColor,
            rects: decoded.rects,
            text: decoded.text.map { safeString($0, fallback: "") }.flatMap { $0.isEmpty ? nil : $0 },
            note: decoded.note.map { safeString($0, fallback: "") }.flatMap { $0.isEmpty ? nil : $0 },
            isAiGenerated: decoded.isAiGenerated,
            createdAt: decoded.createdAt,
            updatedAt: decoded.updatedAt
        )
    }
}

// MARK: - Chat Message
struct ChatMessage: Codable, Identifiable {
    let id: String
    var role: MessageRole
    var text: String
    var timestamp: Date
    /// UI-only flag: marks a locally generated error bubble so the view can
    /// render an inline retry button. Optional so payloads persisted before
    /// this field decode fine (nil). Never written to the chats table.
    var isError: Bool?

    enum MessageRole: String, Codable {
        case user
        case model
    }

    init(
        id: String = UUID().uuidString,
        role: MessageRole,
        text: String,
        timestamp: Date = Date(),
        isError: Bool? = nil
    ) {
        self.id = id
        self.role = role
        self.text = text
        self.timestamp = timestamp
        self.isError = isError
    }
}

// MARK: - Quiz
struct QuizQuestion: Codable, Identifiable {
    let id: Int
    var question: String
    var options: [String]
    var correctAnswerIndex: Int
    var explanation: String?
}

// MARK: - Translation Result
struct TranslationResult: Codable {
    var original: String
    var translated: String
    var detectedLanguage: String
}

// MARK: - Detailed Translation Result
/// Depth layer of the quick-translation popup: a context-aware full
/// translation plus alternative senses for short selections.
struct DetailedTranslationResult: Codable, Equatable {
    var contextualTranslation: String
    /// Alternative renderings (2-4 for words/short phrases, empty for passages).
    var alternatives: [String]
}

// MARK: - Translation History Entry
/// A completed quick-translation persisted for spaced review
/// (Notebook > Çeviriler category).
struct TranslationHistoryEntry: Identifiable, Equatable {
    let id: String
    let fileId: String
    let fileName: String
    let sourceText: String
    let translatedText: String
    let createdAt: Date

    var shortDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd MMM"
        formatter.locale = Locale(identifier: "tr_TR")
        return formatter.string(from: createdAt)
    }
}

// MARK: - Selection Data
struct SelectionData {
    var text: String
    var rect: CGRect
    var pageNumber: Int
}
